### ISSUE TITLE
Restart WiFi if settings change

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#141]
After a user has entered new WiFi credentials, reset the WiFi reconnect timeout so that the system immediately (or shortly) reattempts to start network.

**Comment by LeeLeahy2** [comment]
Fixed with PR #248

**Comment by nseidle** [comment]
This is in [v1.0](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.0).
