### ISSUE TITLE
Create a priority of corrections

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#149]
Corrections can come from a variety of sources included but not limited to:

* External Radio
* Bluetooth
* WiFi IP (PointPerfect/MQTT)
* WiFi TCP (NTRIP Client)
* Ethernet IP (PointPerfect/MQTT)
* Ethernet TCP (NTRIP Client)
* L-Band
* Cellular (LARA)
* LoRa Radio
* ESP-Now

The user needs to be given a way to state the priority of a given source.

**Comment by nseidle** [comment]
@PaulZC - I think you've got the settings in the v0.9 release, but the actual control/limiting of corrections based on those settings was not in v0.9. We'll get it into the RC soon (once I can review your PR).

**Comment by PaulZC** [comment]
This is (I think) complete now. The new code is in the release_candidate branch. But it has not yet made it into an RC .bin.

On EVK, I'm able to prioritise L-Band over IP (MQTT), and vice-versa. The code also updates the ZED UBLOX_CFG_SPARTN_USE_SOURCE (L-Band / IP) as needed when swapping between the two.

**Comment by nseidle** [comment]
This is in [v1.0](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.0).
