### ISSUE TITLE
Implement localized IP based corrections

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#150]
https://developer.thingstream.io/guides/location-services/pointperfect-localized-distribution

**Comment by nseidle** [comment]
This is related to issue #144.

**Comment by PaulZC** [comment]
See #144 for the latest update and code changes

**Comment by PaulZC** [comment]
Resolved in #403

**Comment by nseidle** [comment]
This is in release [v1.3](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.3).
