### ISSUE TITLE
Add AssistNow support

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#151]
Subscribe to mga topic. Once we achieve GPS fix, move to /pp/ubx/mga/updates topic.

See [pointperfect_client.py](https://portal.thingstream.io/app/downloads/pointperfect) for an example implementation.

**Comment by PaulZC** [comment]
Implemented in #403

**Comment by nseidle** [comment]
This is in release [v1.3](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.3).
