### ISSUE TITLE
EVK - SW Maps cannot read GNSS data over BLE

### ISSUE THREAD

**Issue by doug-foster** [sparkfun/SparkFun_RTK_Everywhere_Firmware#224]
### Subject of the issue
SW Maps on iPhone can scan, discover "EVK Rover-8F06" via BLE. Two behaviors:
1) earlier RC version would connect and stay connected, but no GNSS data received.
2) latest RC version connects then disconnects immediately.

### Your workbench
* release_candidate branch - 2024-04-05@14-43-51 - RTK_Everywhere_rc
* Instrument Model = SparkFun RTK or Generic NMEA, same behavior
![iPhone](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/6da6f3e1-b989-44a7-a40f-a66a99c81c74)
![iPhone - SW Maps - internal GNSS](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/761cadcc-017e-414d-9249-a3697fee8d0d)

![SW Maps](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/9d4f43c9-1967-440d-ba99-3f9d701e4761)
<img width="826" alt="u-Center" src="https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/d04c895e-a157-4150-9642-32118ca3177c">
<img width="826" alt="u-Center" src="https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/cb14fe6d-ade7-4b31-8701-ef0956c39905">

### Steps to reproduce
Connect to EVK via BLE

### Expected behavior
Should see GNSS data in SW Maps.

### Actual behavior
Do not see GNSS data in SW Maps. Prior RC version (2 days ago?) would connect & I could see some location data using "nRF Connect" app on iPhone, but not in SW Maps.
![iPhone - nRF Connect - characteristic data from EVK](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/3e50bb58-1988-42f5-a35b-463ac9bd0232)
![iPhone - Bluefruit Connect - can discover EVK](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/f45fca4a-5e40-4b34-a0cb-10ed3c5056fa)
![iPhone - Bluefruit Connect - characteristic data from EVK](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/88458252-e367-4642-8ece-a82a9684e31d)

**Comment by PaulZC** [comment]
I think I'm seeing the same thing. I can connect to Torch via BLE from SWMaps on iOS. But with EVK, I can see it and connect to it, but I don't get any position information...

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/f1f883ee-d699-408c-864a-11554d5ea0f9)

**Comment by doug-foster** [comment]
Yes, same as what I saw Paul. 

Bummer is I can't use the EVK on my plantation project (ask @nseidle) until it works. I know the Torch is priority, but any idea on where this sits on the EVK fix list?

Ping me anytime & I can do a new build & test.

**Comment by doug-foster** [comment]
Tested again with a new build of https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/tree/release_candidate on 2024-04-22. Still broken :-(.

**Comment by PaulZC** [comment]
Hi Doug,

Just to confirm my earlier email:
* This is a hardware limitation on the EVK v1.0 PCB
* It is resolved on EVK v1.1 PCB
* There is a software workaround, but it is messy and I don't propose to implement it for the five EVK v1.0's in the wild...
* The best solution is to modify the v1.0: three cut traces and four jumper wires turn it into a v1.1
* We'll get a modified board to you ASAP and point you - and the other EVK champions - at the modified code to match

I'll leave this open until you have hardware, and the firmware has been updated to match EVK v1.1.

Best,
Paul

**Comment by nseidle** [comment]
This is in [v1.0](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.0).
