### ISSUE TITLE
Serial menu - GNSS REceiver - typo option 2

### ISSUE THREAD

**Issue by doug-foster** [sparkfun/SparkFun_RTK_Everywhere_Firmware#225]
### Subject of the issue
Serial menu - GNSS Receiver - typo option 2

### Your workbench
release_candidate branch - 2024-04-05@14-43-51 - RTK_Everywhere_rc
serial menu

### Steps to reproduce
serial menu

### Expected behavior
nit - probably should be a space before the word "Note:"
maybe consider \n before "Note:" ?

### Actual behavior
<img width="562" alt="Screenshot 2024-03-24 at 2 18 42 PM" src="https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/bb4ec03a-6da5-49f2-8bd7-c2db1b560311">

**Comment by nseidle** [comment]
It's your terminal rendering a \t tab character in an odd way. Here's what it looks like in TeraTerm:

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/117102/d76697e9-51b0-4b2f-90a5-1f70a4e4e77a)

I'll change it to 8 spaces.
