### ISSUE TITLE
EVK Selecting the wrong ZTP token

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#231]
pointperfectGetToken() gets called when a provision event happens. This function looks at the available hardware and selects the ZTP token.

In the case of the EVK, a user may have select IP corrections (only) but the logic points them to the ppLbandPaidToken, which L-Band reception may or may not be available in the user's locale.

Solution: 
* Make the PointPerfect menu display service options that are compatible with the available hardware
* Make pointperfectGetToken() pick the token connected with that service level. ie if a user wants IP access only, they should be directed to the IP only ZTP token.

**Comment by PaulZC** [comment]
Fixed in release_candidate. We now have LBAND_IP FREE and PAID tokens. The EVK defaults to these.

This avoids devices having to be whitelisted on both IP-only and L-Band-only plans, and potentially being charged for both plans...

**Comment by PaulZC** [comment]
Removing the label. The code changes are in the release_candidate branch. But it hasn't yet been built into a RC .bin.

**Comment by nseidle** [comment]
RC pushed. Tag added.

**Comment by nseidle** [comment]
This is in [v1.0](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.0).
