### ISSUE TITLE
Probable obsolete code in menuPP.ino

### ISSUE THREAD

**Issue by PaulZC** [sparkfun/SparkFun_RTK_Everywhere_Firmware#235]
@nseidle : please check if [these two lines](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/blob/57fe7bd71340f701869b8d2254a6cba70813ce12/Firmware/RTK_Everywhere/menuPP.ino#L256-L258) can / should be removed. They look wrong to me.

**Comment by nseidle** [comment]
I believe they are still good/valid. This checks to see if the developer token (ie no local token.h file) is used, or if the actual token is passed in via workflow. This is a very helpful debug message to know/see.

**Comment by PaulZC** [comment]
Oh! Silly me... I mistook memcmp for memcpy.... Closing. I'll remove the comment at the next opportunity.

**Comment by nseidle** [comment]
Np!
