### ISSUE TITLE
PointPerfect - no way to configure PP using account MQTT credentials

### ISSUE THREAD

**Issue by doug-foster** [sparkfun/SparkFun_RTK_Everywhere_Firmware#246]
### Subject of the issue
No options to enter PointPerfect account credentials.

### Your workbench
- EVK
- https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/tree/release_candidate/Firmware/RTK_Everywhere

### Steps to reproduce
<img width="737" alt="Screenshot 2024-04-23 at 1 11 16 PM" src="https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/86d4130a-bb8c-44b6-9d0b-27c0a720d70b">

### Expected behavior
Accept MQQT credentials via both web & serial config menus
<img width="1114" alt="Screenshot 2024-04-23 at 1 16 31 PM" src="https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/8713605/cff31402-d769-4b67-9138-f675c53facb5">

### Actual behavior
see screen snapshot of serial menu

**Comment by nseidle** [comment]
![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/117102/daad4a2c-ab82-44de-8b5f-0564969408b0)

It looks like your token is malformed. Are you using a release candidate binary or compiling locally? The Release Candidate binaries include this information but locally compiled binaries [are forced to use](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/blob/main/Firmware/RTK_Everywhere/menuPP.ino#L8) the `DEVELOPMENT_TOKEN`.

If you'd like to use your own credentials, create a ZTP profile, copy/paste that token # into the 'ThingStream Device Profile Token' menu, then you can provision the device on your account. Only one other person has requested a custom key path so it's not well trodden.

**Comment by doug-foster** [comment]
Compiled locally. [RTK_Everywhere_Firmware_RC-Apr_17_2024.bin](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware_Binaries/blob/main/RTK_Everywhere_Firmware_RC-Apr_17_2024.bin) would not run (but would when compiled locally), stuck in boot loader loop. I can retry with both [RTK_Everywhere_Firmware_RC-Apr_23_2024.bin](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware_Binaries/blob/main/RTK_Everywhere_Firmware_RC-Apr_23_2024.bin) and a local compile ... however ...

I think I understand now. PointPerfect ZTP (Zero Touch Provisioning & whitelisting a device) profiles are not available under a free PP developer (IP only) account.

RTK_Everywhere can only be used with a full, _paid_ PP subscription (which could yield a ZTP profile token). The lowest cost PP account level to support this would probably be "[PointPerfect 100H - 100 hour IP only @ $5.90 per month](https://portal.thingstream.io/pricing/laas/laaspointperfect)." I'll have to confirm.

**Comment by nseidle** [comment]
I'm going to close this. The firmware is designed so that users do not need a ThingStream account. If they desire, they can use their own ZTP token, or they can enter the key/expirations directly.

**Comment by doug-foster** [comment]
Agreed - ZTP tokens can be created for _all_ PP plans.
