### ISSUE TITLE
Code requires a restart to enable RTCM1019/1020/1042/1046 for PPL on Torch

### ISSUE THREAD

**Issue by PaulZC** [sparkfun/SparkFun_RTK_Everywhere_Firmware#260]
The RTCM1019/1020/1042/1046 messages needed by the PPL are **only** enabled by ```um980EnableRTCMRover```, and only if ```settings.enablePointPerfectCorrections``` is (already) ```true```.

If we are enabling PointPerfect for the first time via the menu, the keys get downloaded, the PPL is set online, the IP corrections start to arrive, but the PPL can't work its magic because the RTCM messages aren't enabled. It's because ```um980EnableRTCMRover``` isn't re-called:

* ```um980EnableRTCMRover``` gets called by ```um980ConfigureRover``` from ```gnssConfigureRover``` - but only from state ```STATE_ROVER_NOT_STARTED```

* ```um980EnableRTCMRover``` is also called by ```um980SetRate``` from ```gnssSetRate``` - but only from the GNSS menu or ```setLogTestFrequencyMessages```

We need a way to force-enable RTCM1019/1020/1042/1046 for the PPL when enabling PointPerfect for the first time.

Maybe, we require a mandatory restart after enabling PointPerfect? That would solve it...

**Comment by nseidle** [comment]
This is in [v1.0](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.0).
