### ISSUE TITLE
WiFi Config not rendering multiple NTRIP Servers

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#266]
The WiFi config interface is not rendering all the possible NTRIP Servers. The serial menu implements 4, WiFi config shows one.

**Comment by PaulZC** [comment]
They're there. But we do need to change the names so they start at 1...

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/6b3bbe1b-ce86-43f7-9843-12c03a708ab1)

**Comment by PaulZC** [comment]
Resolved in #269
