### ISSUE TITLE
Add update PointPerfect keys button in WiFi Config

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#275]
We have AP + STA mode active for firmware checking and update, use the same methods to allow user to update PointPerfect keys.

**Comment by PaulZC** [comment]
I'm renaming ```forceKeyAttempt``` to ```requestKeyUpdate```

**Comment by PaulZC** [comment]
OK. This is in #403 too. Changes are: b75f937603429fe5f591f102d118e3de1e3aaf9d

**Comment by nseidle** [comment]
This is in release [v1.3](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.3).
