### ISSUE TITLE
Add new features to WiFi Config

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#284]
New features that need to be rendered on WiFi Config page:

* HAS/E6 enable/disable under GNSS
* Add Ports menu for Torch.
* Add USB GNSS output enable/disable under Ports

**Comment by nseidle** [comment]
Remove Debug Zone / Reset counter

**Comment by nseidle** [comment]
Update Torch default ARP and tooltip.

**Comment by nseidle** [comment]
Add rebootSeconds feature to system menu

**Comment by nseidle** [comment]
* Add Tilt menu.
* Enable/disable tilt
* Pole length

**Comment by nseidle** [comment]
Add auto-firmware update to system menu

**Comment by nseidle** [comment]
Add Measurement scale to system menu

**Comment by nseidle** [comment]
Add Beeper control to system menu

**Comment by PaulZC** [comment]
```Enable Tilt Compensation``` and ```Pole Length (m)``` are already in GNSS Config. Let me know if they should be somewhere else.

**Comment by nseidle** [comment]
Ah! Good to know. We should break it out to its own grouping.

**Comment by nseidle** [comment]
This is in release [v1.3](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.3).
