### ISSUE TITLE
Torch "...device not whitelisted..." message provides a URL to a webpage for L-Band Facet provisioning

### ISSUE THREAD

**Issue by tonycanike** [sparkfun/SparkFun_RTK_Everywhere_Firmware#320]
### Subject of the issue

Here's the error message with the URL that goes to a provisioning page for L-Band Facets.

```
Connecting to: https://api.thingstream.io/ztp/pointperfect/credentials
This device is not whitelisted. Please contact support@sparkfun.com or goto https://www.sparkfun.com/pointperfect to get your subscription activated. Please reference device ID: 64B7xxxxxxx

```

The URL in the error message goes to a webpage that's all about L-Band Facet provisioning.

Oh, and also **there is no form to fill out - just a big blank whitespace.**

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/17495167/f9faf6e9-ab28-4045-bfae-fe959ff090cc)

### Your workbench

```
LittleFS Started
PSRAM Size (bytes): 2095087
I2C Devices:
  0x08 - HUSB238 Power Delivery Sink Controller
  0x0B - BQ40Z50 Battery Pack Manager / Fuel gauge
  0x5C - MP27692A Power Management / Charger
  0x60 - ATECC608A Cryptographic Coprocessor
SparkFun RTK Torch v1.1
GNSS UM980 online
UM980 firmware: 11833
Profile 'Profile1' loaded
Fuel gauge configuration complete
Batt (43%): Voltage: 7.37V Discharging: 7.60%/hr
Charger configuration complete
UM980 configuration updated
No GNSS date/time available for system RTC.
Bluetooth SPP and BLE broadcasting as: Torch Rover-0026
STATE_ROVER_NOT_STARTED --> STATE_ROVER_NO_FIX
Batt (43%): Voltage: 7.37V Charging: 7.41%/hr
No GNSS date/time available for system RTC.
```

**Comment by nseidle** [comment]
We'll get that fixed. Correct link: https://www.sparkfun.com/rtk_torch_registration

What browser are you using? It's rendering for me:

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/117102/16fcd0b2-e7d8-4012-957f-fdccf6c13de5)

**Comment by tonycanike** [comment]
I was using Chrome on a W10 machine.  I've since closed and opened Chrome and the form fields appeared (sparkfun.com/pointperfect).

**Comment by nseidle** [comment]
Working for me but I'll bring it up with our web folks:

![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/117102/cc9b56cb-df72-45d5-aa40-1c02888e1f26)

**Comment by nseidle** [comment]
Thanks for reporting! The landing page is now linked to platform. Should enter RC shortly.
