### ISSUE TITLE
(release_candidate) Code reboots after 1 minute if rebootMinutes is zero

### ISSUE THREAD

**Issue by PaulZC** [sparkfun/SparkFun_RTK_Everywhere_Firmware#328]
There's a flaw in updatePeriodicDisplay, causing a reboot after 1 minute if rebootMinutes is zero (default). Corrected in:

27a607b2e1c62e93433de70b14fe88024b515a58
477433337acb9f8aa99d8531e8b886762f471fbb
1d85f13c5773d0c3929438765828c14cfeede4d9

**Comment by nseidle** [comment]
This is in release [v1.3](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.3).
