### ISSUE TITLE
Sparkfun Connection Guide-QField on IOS

### ISSUE THREAD

**Issue by craigr78** [sparkfun/SparkFun_RTK_Everywhere_Firmware#332]
Could you provide step by step instructions for connecting the Facet L band to an IOS device using QField?

**Comment by nseidle** [comment]
This has been added [here](https://docs.sparkfun.com/SparkFun_RTK_Everywhere_Firmware/gis_software_ios/#qfield) along with [ArcGIS Survey123](https://docs.sparkfun.com/SparkFun_RTK_Everywhere_Firmware/gis_software_ios/#arcgis-survey123).
