### ISSUE TITLE
(release_candidate) Is tcpServer tied to WiFi?

### ISSUE THREAD

**Issue by PaulZC** [sparkfun/SparkFun_RTK_Everywhere_Firmware#336]
Looking at the code in ```TcpServer.ino```, it appears to be tied to WiFi - with no mention of Ethernet or the network layer:

https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/blob/45aeb81a4e27fb4e7ae52d45f1a485853563c03d/Firmware/RTK_Everywhere/TcpServer.ino#L68

https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/blob/45aeb81a4e27fb4e7ae52d45f1a485853563c03d/Firmware/RTK_Everywhere/TcpServer.ino#L229-L237

**Comment by PaulZC** [comment]
Will be resolved by #402

**Comment by nseidle** [comment]
This is in release [v1.3](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.3).
