### ISSUE TITLE
(EVK) ZED not configuring constellations correctly

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#354]
Display started
      SparkFun RTK EVK d99.99
      ZED-F9P firmware: HPG 1.32
      GNSS ZED online
      Profile 'Profile1' loaded
      Module failed config block 1
      ZED-F9x configuration update
      NEO-D9S firmware: PMP 1.04

To replicate: Turn off the GPS constellation and exit menus. ZED should reconfigure but does not. Resetting unit does not fix the problem and throws a config block 1 error.

**Comment by PaulZC** [comment]
Oh yeah... This was a big old mess. The constellations in ```settings.ubxConstellations``` have been alphabetised, but ```zedSetConstellations``` was still hard coded to the old order. Fixed in #374
