### ISSUE TITLE
(EVK) Device reporting large rover inaccuracy after factory reset

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#356]
E (7021) w5500.mac: emac_w5500_init(823): reset w5500 failed
      E (7021) esp_eth: esp_eth_driver_install(228): init mac failed
      [  7027][E][ETH.cpp:659] beginSPI(): SPI Ethernet driver install failed: 263
      Rover Accuracy (m): 429496.719, SIV: 0 GNSS State: No Fix
      System time set to: Wednesday, June 19 2024 17:50:40
      Rover Accuracy (m): 429496.719, SIV: 0 GNSS State: No Fix
      Rover Accuracy (m): 429496.719, SIV: 0 GNSS State: No Fix
      Rover Accuracy (m): 429496.719, SIV: 0 GNSS State: No Fix

To replicate, factory reset a device and the rover accuracy will be huge.

This is likely due to GNSS reset. Should we just not display rover accuracy until we get a fix?

**Comment by PaulZC** [comment]
We have no control over the 429496.719. That's just the default hAcc while the module gets a fix. Suspiciously close to 0xFFFFFFFF * 0.1mm!

We can easily cap this at ">30m" [like we do on the display](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/blob/fcaf7cab99e4c40ff118e5b8d8c9e332135b58f5/Firmware/RTK_Everywhere/Display.ino#L1306).

**Comment by PaulZC** [comment]
Fixed in #376
