### ISSUE TITLE
Remove charging config menus for non-battery devices

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#358]
EVK in system menu:

      c) Shutdown if not charging: Disabled

We should consider hiding menus like this for devices that do not have support for it. There are likely other menus as well. I am only considering top level menus, not debug menus, that normal users may come across.

**Comment by PaulZC** [comment]
To fix this _properly_, we should create a table of menu entries and tag each one with applicable platforms...

Meanwhile, #377 will have to suffice... ;-)
