### ISSUE TITLE
Explicitly set default network

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#360]
TCP/UDP Menu:

    d) Default network: Hardware Default

What does 'hardware default' mean? I don't think I like this. I expect one or the other. If specific platforms have different defaults, that's fine, but let's not make the user think or have to look up what the default is for their platform. We should just tell them.

**Comment by PaulZC** [comment]
This is a job for @LeeLeahy2 . As far as I can tell, it is [networkGetActiveType](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/blob/fcaf7cab99e4c40ff118e5b8d8c9e332135b58f5/Firmware/RTK_Everywhere/Network.ino#L482-L491) that defines the default. Maybe we need to add an extra table which defines the default for each platform - and report that "Default network: Hardware Default (Ethernet)"?
