### ISSUE TITLE
Move `Default network` to Ethernet menu

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#361]
Currently under TCP/UDP network:

    d) Default network: Hardware Default

Having this in the TCP menu doesn't make sense to me. A 'Network' menu would make more sense, but in the absence of that, the Ethernet menu makes most sense as it disappears if a platform doesn't have ethernet, and hence, fail over disappears as well.

**Comment by PaulZC** [comment]
Fixed by #378

**Comment by nseidle** [comment]
This is in release [v1.3](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.3).
