### ISSUE TITLE
(EVK) NTP reports UDP error

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#371]
To replicate:

* Confirm ethernet is connected
* Factory reset
* Enter into NTP mode from system menu

A non-stop error is reported. The display looks pretty good. 

      [ 23006][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9
      [ 23013][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9
      [ 23020][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9
      [ 23027][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9
      [ 23034][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9
      [ 23041][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9
      [ 23048][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9
      [ 23055][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9
      [ 23062][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9
      [ 23069][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9
      [ 23076][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9
      [ 23083][E][NetworkUdp.cpp:309] parsePacket(): could not receive data: 9

**Comment by PaulZC** [comment]
Yeah... NTP was very broken. Resolved in #404

**Comment by nseidle** [comment]
This is in release [v1.3](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.3).
