### ISSUE TITLE
(EVK) Fix blinking NTP clock icon

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#372]
To replicate:

* Go into NTP mode

The clock icon is continually blinking. Is this indicating something or an error? It would ideally progress like the hands on a clock face without blinking.

**Comment by PaulZC** [comment]
The clock icon will blink until the RTC has been synchronised accurately to GNSS time.

If you were running this on v1.0 hardware, the RTC would never sync...

**Comment by nseidle** [comment]
Yep! Thanks for pointing out my mistake. All good.
