### ISSUE TITLE
No Beep in latest beta JUN 24

### ISSUE THREAD

**Issue by APOS80** [sparkfun/SparkFun_RTK_Everywhere_Firmware#384]
### Subject of the issue
Double press on Torch to get to WIFI doesnt give a Beep.
So har to know if its active.               

### Your workbench
* What version of RTK firmware are you running? This can be found when the serial menu is opened (also in the settings.txt file, and in the serial output at power up).
Beta firmware from Jun 24
* What radios are you using: Bluetooth, WiFi, and/or ESP-Now? What app are you using to connect over Bluetooth? Are you transmitting NTRIP back to the device?
Phone
* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post any log files from serial output that may have been generated.
Double press Rover(Torch) button
### Expected behavior
Tell us what should happen
Beep indicating the WIFI connection is open.

### Actual behavior
Tell us what happens instead
No beep

**Comment by nseidle** [comment]
This is by design. Most beeper functions [are deactivated](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/blob/release_candidate/.github/workflows/compile-rtk-everywhere.yml#L52) in locally compiled and release candidates.
