### ISSUE TITLE
(EVK) Avoid IP shuttling display in NTP mode

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#414]
Low priority. The IP address on EVK is shown statically (currently I have 6 digits xx.x.x.xx) in Rover mode. In NTP mode, the IP address is shown at the top of the display and bounces back and forth. 

We have plenty of space on the display. Allow full IP address (ie 255.255.255.255) to be shown without the need for 'shuttling'.

**Comment by PaulZC** [comment]
Resolved by #496

**Comment by nseidle** [comment]
This was rolled out in production release v2.0.
