### ISSUE TITLE
Display correction source

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#418]
I'm currently using an EVK. The device is in RTK Fix and has 14mm HPA, but it's not immediately clear to me how. It doesn't appear to be L-Band or Bluetooth. It must be IP via PointPerfect, but 14mm is stellar. Ah, no, it was an NTRIP client I didn't realize was on.

Should we periodically print the source being used? 

Should we display an icon showing the source? This could get messy on the screen, but we have plenty of room.

**Comment by PaulZC** [comment]
I like the idea of displaying an icon. And we have room for it on the bottom row - between the full IP address and the logging icon. Let's identify the most recently pushed corrections source:

* CORR_RADIO_EXT - use DynamicModel_1_Portable ?
  * ![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/0e0d6478-cb67-43bf-a668-bfeb32c701aa)
* CORR_ESPNOW - use ESPNOW_Symbol_3 ?
  * ![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/ada099a6-6d35-4f10-8638-1196a8ecbd94)
* CORR_RADIO_LORA - new "[RKO Pictures](https://en.wikipedia.org/wiki/RKO_Pictures#/media/File:RKO_Radio_Pictures_transmitter_ident.jpg)" antenna mast icon?
  * ![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/da5a380e-1e4d-4c96-9764-7429454696b2)
* CORR_BLUETOOTH - use BT_Symbol ?
  * ![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/874a5621-96b5-4124-b51b-632d2a61c8af)
* CORR_TCP - this is NTRIP, so maybe the SNIP logo?
  * ![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/0c64fddf-491e-49d1-b131-559e74ce791b)
* CORR_LBAND - use SIV_Antenna ?
  * ![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/2d2d3e5e-026d-4be5-b533-06df6a40a06e)
* CORR_IP - this is PointPerfect so maybe a simplified 
  * ![image](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/assets/5690545/a8072d8c-9b45-4491-8325-18cc72fa1358)

**Comment by nseidle** [comment]
WFM! How to signify the word 'source'? Maybe just put these icon types next to the current down arrow? I believe the down arrow only blinks with Bluetooth and WiFi traffic. If we can expand this to the other sources, I think that would be great.

**Comment by nseidle** [comment]
Lee has laid the groundwork [here](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/pull/452/files). Priorities menu is now showing who/what is active. `correctionGetSourceName()` is helpful.

![image](https://github.com/user-attachments/assets/b653e430-d4cd-4537-bd38-48fc63a9d949)

**Comment by PaulZC** [comment]
The changes for EVK are in #492

**Comment by PaulZC** [comment]
Full set:

    CORR_RADIO_EXT
    CORR_ESPNOW
    CORR_RADIO_LORA
    CORR_BLUETOOTH

![image](https://github.com/user-attachments/assets/4c9916b1-658a-490b-8b8a-8ef8d727aa85)

    CORR_USB
    CORR_TCP
    CORR_LBAND
    CORR_IP

![image](https://github.com/user-attachments/assets/ee054c88-8d93-42cf-bdc6-d3437fcbc345)

**Comment by nseidle** [comment]
Beauty!

**Comment by PaulZC** [comment]
On 64x48, I went with blinking the source over the Horizontal accuracy. It only happens when you are in RTK Float / Fix. The normal dual-crosshair is shown for 6 out of 8 of the 0.5 second intervals. The correction source is shown for the other two. For Float, the source blinks to match the blinking crosshair. Let me know if this hits the spot...

![image](https://github.com/user-attachments/assets/3b1d1dd1-8d1b-4d34-be91-5956c9c85e92)
![image](https://github.com/user-attachments/assets/ea1325dd-0ac6-458c-8833-e694cb66db15)

**Comment by nseidle** [comment]
This looks great to me!

**Comment by nseidle** [comment]
This was rolled out in production release v2.0.
