### ISSUE TITLE
Tilt setting not present in WiFi “web” settings.

### ISSUE THREAD

**Issue by APOS80** [sparkfun/SparkFun_RTK_Everywhere_Firmware#441]
### Subject of the issue
All settings from terminal isn’t present in WiFi web settings.

The setting for coordinate in antenna Center or pole tip missing

### Your workbench
* What version of RTK firmware are you running? This can be found when the serial menu is opened (also in the settings.txt file, and in the serial output at power up).
1.3
* What radios are you using: Bluetooth, WiFi, and/or ESP-Now? What app are you using to connect over Bluetooth? Are you transmitting NTRIP back to the device?
Bluetooth/wifi
* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post any log files from serial output that may have been generated.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

**Comment by nseidle** [comment]
This was rolled out in production release v2.0.
