### ISSUE TITLE
Compilation error when IM19_IMU funcionality removed by line comment in RTK_Everywhere.ino configuration section

### ISSUE THREAD

**Issue by mlewandowski** [sparkfun/SparkFun_RTK_Everywhere_Firmware#442]
### Subject of the issue
RTK_Everywhere firmware in not possible to be compiled when IM19_IMU funcionality is disabled in RTK_Everywhere.ino

### Your workbench
* What version of RTK firmware are you running? This can be found when the serial menu is opened (also in the settings.txt file, and in the serial output at power up).
I'm trying to compile latest RTK_Everywhere firmware where commit head was "Merge pull request #437 from sparkfun/EVK_docs"

* What radios are you using: Bluetooth, WiFi, and/or ESP-Now? What app are you using to connect over Bluetooth? Are you transmitting NTRIP back to the device?
Issue not related to highlighted details

* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post any log files from serial output that may have been generated.
1. Compile execution based on information available on https://docs.sparkfun.com/SparkFun_RTK_Everywhere_Firmware/firmware_update/#updating-um980-firmware
2. Comment out #define COMPILE_IM19_IMU in RTK_Everywhere.ino
3. Compile command execution:
arduino-cli compile 'Firmware/RTK_Everywhere' --build-property build.partitions=RTKEverywhere --build-property upload.maximum_size=3145728 --fqbn esp32:esp32:esp32:FlashSize=16M,PSRAM=enabled
4. Compilation error:
SparkFun_RTK_Everywhere_Firmware\Firmware\RTK_Everywhere\Tasks.ino:484:9: error: 'nmeaApplyCompensation' was not declared in this scope; did you mean 'tiltApplyCompensation'?
  484 |         nmeaApplyCompensation((char *)parse->buffer, parse->length);
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         tiltApplyCompensation

### Expected behavior
Possible compilation when IM19_IMU funcionality is disabled in RTK_Everywhere.ino

### Actual behavior
Not posible to compile RTK_Everywhere when IM19_IMU funcionality is disabled

**Comment by nseidle** [comment]
Sorry about that! Fixed [here](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/commit/8aca9ea55efa2e515715dc58be9435228936d1c1).
