### ISSUE TITLE
Ham Radio sync

### ISSUE THREAD

**Issue by wtelliot** [sparkfun/SparkFun_RTK_Everywhere_Firmware#443]
### Subject of the issue
I think you missed a key function that should be added.   Amateur Radio operators are always looking for ways to improve their radios and test equipment accuracy plus the reliability of their communications.  By adding a 10 mhz output and a 1PPS output this device could be a very good tool that Amateur Radio Operators would want.
There are many videos out there of improving performance using GPS based frequency standards.

**Comment by PaulZC** [comment]
Hi @wtelliot ,

The new [SparfFun RTK EVK](https://www.sparkfun.com/products/24342) provides access to the GNSS TP (Timing Pulse) signal. The default is 1Hz, but the ZED-F9P supports frequencies up to 10MHz. The [RTK Everywhere firmware](https://docs.sparkfun.com/SparkFun_RTK_Everywhere_Firmware/menu_ports/#pulse-per-second) allows you to set the pulse duration. A stand-alone frequency example is available [here](https://github.com/sparkfun/SparkFun_RTK_EVK/blob/main/Example_Sketches/5_4_GNSS_TP_Frequency/5_4_GNSS_TP_Frequency.ino).

Best wishes,
Paul
