### ISSUE TITLE
(Torch) I2C Error on devices with one I2C bus

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Everywhere_Firmware#445]
In system menu, v1.3

      Connected via BLE:
      System Status
      2024-07-17 20:22:35.870
      ERROR: I2C bus not responding!
      GNSS: Online - UM980 firmware: 11833

I suspect this is because of the EVK and, because it is expecting a 2nd I2C bus, this is an erroneous error.

**Comment by PaulZC** [comment]
Please see https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/commit/b6a08a85ad5da0324788d0bd45ef56d9abbd08d4#commitcomment-144367239

**Comment by nseidle** [comment]
Fix in place in [v1.4](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/releases/tag/v1.4).
