### ISSUE TITLE
WiFi Config - Base Configuration - NTRIP Server (1) - Save Configuration fails...

### ISSUE THREAD

**Issue by PaulZC** [sparkfun/SparkFun_RTK_Everywhere_Firmware#480]
Reported [here](https://portal.u-blox.com/s/question/0D5Oj00000Qu4oiKAB/i-would-like-to-transmit-rtcm-from-sparkfun-rtk-evk-via-the-ntrip-server) and [here](https://community.sparkfun.com/t/how-to-setup-rtcm-via-ntrip-tcp-for-precise-point-positioning-ppp/60341).

We have a gremlin in main.js when using ```checkElementString``` on the NTRIP Server (1) configuration:

![image](https://github.com/user-attachments/assets/fab023cc-2cb0-44bc-8da7-2a5182f71413)

Investigating...

**Comment by PaulZC** [comment]
This issue has already been resolved in the release_candidate branch...

I've created a separate "hotfix" branch which includes: the fix for this issue; and increases the number of corrections sources to 8.

https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/commits/Hotfix_%23480/

**Comment by PaulZC** [comment]
@nseidle : this is done. Please release an RC from the Hotfix branch when time permits.

**Comment by PaulZC** [comment]
I suggest we **don't** merge the Hotfix branch into main. It is safe to do so, the changes should be identical to the changes already in release_candidate, but they'll probably appear as a conflict...

**Comment by nseidle** [comment]
Nice fix! RC has been posted [Sep-25](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware_Binaries/blob/main/RTK_Everywhere_Firmware_RC-Sep_25_2024.bin).

**Comment by nseidle** [comment]
This was rolled out in production release v2.0.
