### ISSUE TITLE
Missing a dedicated app for SparkFun rtk rovers.

### ISSUE THREAD

**Issue by APOS80** [sparkfun/SparkFun_RTK_Everywhere_Firmware#497]
### Subject of the issue
There’s many expensive apps and apps lacking functionality.

Surpad has several versions and I don’t know which works best with my Torch.

I would like to se an open source app for Sparkfun rovers.

### Your workbench
Torch

### Steps to reproduce
Tell us how to reproduce this issue. Please post any log files from serial output that may have been generated.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

**Comment by nseidle** [comment]
We are a hardware company and do not have the ability to do a dedicated GIS app. If there is a group that would like to start a project, we are happy to support them.
